version: '3.1'

services:

  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  backend:
    build: backend
    volumes:
      - /app/node_modules
      - ./backend:/app/
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_DB: ${DATABASE_DB}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

  frontend:
    build: frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app/
    ports:
      - "3000:3000"