version: '3.1'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}

  backend:
    build: backend
    volumes:
      - ./backend:/app/
      - /app/node_modules
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

  frontend:
    build: frontend
    volumes:
      - ./frontend:/app/
      - /app/node_modules
    ports:
      - "3000:3000"